### PR TITLE
Properly export and import the `mergePath` helper

### LINKED ISSUE #74: ReferenceError: mergePath is not defined
The library throws an error when attempting to run `signOut` in version `0.4.1`. It seems `mergePath` didn't make it into the `client` bundle. Here's a workaround: https://github.com/vhscom/svelte-headlessui-starter/blob/trunk/src/routes/account/signout.ts

### PR DESCRIPTION
**Pull request by ohmree**
Fixes #74.

Until this gets merged it's possible to use my branch:

```shell
$ npm rm sk-auth && npm i ohmree/sk-auth#fix-mergepath # or yarn, or pnpm
```

### CODE REVIEW

**Comment by vhscom** [comment]
I tested this locally and, while I was able to call `signOut` it's not clear how to use it properly. @ohmree do you have an example of using signout once it's available? I see in the source code it appears this feature is about one-half baked as there's a commented out `session` import at the top of the page. I'm guessing @Dan6erbond was attempting to model from the [NextAuth signout module](https://github.com/nextauthjs/next-auth/blob/a72f1b6d21da89b4223542006c865862635c027b/packages/next-auth/src/core/routes/signout.ts), had to stop, then decided not to export `signOut` on purpose since the feature isn't complete. What has your experience been?

**Comment by ohmree** [comment]
> What has your experience been?

I actually don't remember, I've since switched to a spa with supabase for auth. 

Sorry I couldn't be more helpful.

**Comment by vhscom** [comment]
No worries. I'm looking at integrating Supabase auth into this to ensure there's no vendor lock in a starter I'm working on. If you wouldn't mind pointing me to what you were able to find (if it's open source) I'd appreciate it. Thanks!

**Comment by vhscom** [comment]
No worries @ohmree. I'm looking at integrating Supabase auth into this library to ensure there's no tech lock-in a starter I'm working on. If you have any pointers to another auth library, I'd love to have a look at the source. Cheers.

**Comment by fusepilot** [comment]
I've read the comments, but don't yet understand the hold up for getting this merged. [signOut.ts](https://github.com/Dan6erbond/sk-auth/blob/main/src/client/signOut.ts) calls a function named `mergePath` [here](https://github.com/Dan6erbond/sk-auth/blob/main/src/client/signOut.ts) and [here](https://github.com/Dan6erbond/sk-auth/blob/main/src/client/signOut.ts), but `mergePath` is not defined anywhere in the file. As a result, I get this runtime error: `ReferenceError: mergePath is not defined` when I call `signOut`.

This PR fixes it for me. Would love to see it merged.

**Comment by vhscom** [comment]
@fusepilot did you try implementing `signOut` after the helper function is fixed? If not, the current approach of failing loudly is more obvious than a helper function which cannot be implemented properly. However, if you got sign out working with the helper fixed it would be useful to know your implementation for sign out.

**Comment by Dan6erbond** [comment]
@vhscom the sign-out functionality is something I have to look into. I'm unsure at the current time if it's done or not, but I believe that the `mergePath` helper should be made available either way, as the "loud fail" is an unintentional warning more than anything else. I'll look into the other issue soon, for now this will be mergerd.

**Pull request merged**
