### PR TITLE
✨ Upgrade to SvelteKit 1.0.0-next.211 and related fixes

### PR DESCRIPTION
**Pull request by lulzneko**
Upgrade the SvelteKit dependency to the latest version, SvelteKit 1.0.0-next.211.

There will also be fixes associated with it.
Mainly related to the following SvelteKit PRs
- https://github.com/sveltejs/kit/pull/3126
- https://github.com/sveltejs/kit/pull/3133

### CODE REVIEW

**Comment by Kelvijn** [comment]
Hope this gets merged quickly! Great job @lulzneko

**Comment by ByronCobb** [comment]
@Kelvijn thank you for the fork. Hopefully @Dan6erbond can merge this asap, as the bug makes this repo unusable.

**Comment by Kelvijn** [comment]
> @Kelvijn thank you for the fork. Hopefully @Dan6erbond can merge this asap, as the bug makes this repo unusable.

Credits to @lulzneko!

Did you get the fork working on your machine? I didn't when installing the package from my github URL, the node module didn't contain any index file only the package.json, tips? 😀

**Comment by timwedde** [comment]
I, too, am blocked by this, would be nice if this could get merged.

**Comment by ByronCobb** [comment]
@Kelvijn I've not yet tried it, but this stackoverflow answer seems to be relevant.
https://stackoverflow.com/a/57503862

I think in short it recommends adding an empty .npmignore to the fork.

**Comment by Dan6erbond** [comment]
Sorry everyone! I missed this breaking change, but good catch @lulzneko. Will merge this ASAP once I get the linting errors to resolve, and I'm glad to see the Svelte team has simplified the way URLs work. Should also improve error tolerance from issues such as #59.

**Pull request merged**
