### PR TITLE
Add Okta Oauth provider

### PR DESCRIPTION
**Pull request by CrispyBacon1999**
Adds a provider for Okta. Can be used using:

```ts
new OktaOAuth2Provider({
    oktaDomain: import.meta.env.VITE_OKTA_DOMAIN as string,
    clientId: import.meta.env.VITE_OKTA_CLIENTID as string,
    clientSecret: import.meta.env.VITE_OKTA_CLIENTSECRET as string
})
```

### CODE REVIEW

**Comment by Dan6erbond** [comment]
Nice! One thing - OktaProvider needs to have the provider and its types exported in `src/providers/index.ts` so that it can be imported as a standard provider.

**Comment by cormacmccarthy** [comment]
@Dan6erbond I'm interested in using Okta as an Oauth provider, so I made your requested changes, but I have no idea how to get them into this PR. They're here: https://github.com/cormacmccarthy/sk-auth

**Comment by vhscom** [comment]
> I'm interested in using Okta as an Oauth provider, so I made your requested changes, but I have no idea how to get them into this PR. They're here: https://github.com/cormacmccarthy/sk-auth

If you based your work off this branch, it's possible for the maintainer to cherry-pick your commit adding the requested work into this branch so it can be tested. If that's the case, please indicate the commits to be cherry-picked or consider opening another Pull Request which wraps up the work and can be used to supersede this one assuming @CrispyBacon1999 is no longer interested in the follow-up work.

**Comment by cormacmccarthy** [comment]
Supersedes #98

**Comment by Dan6erbond** [comment]
Closing as #98 supersedes it.

**Pull request closed without merging**
