### PR TITLE
wip: feat: discord provider

### PR DESCRIPTION
**Pull request by alexstaroselsky**
Add discord oauth2 provider https://discord.com/developers/docs/topics/oauth2

### CODE REVIEW

**Comment by alexstaroselsky** [comment]
Marking as WIP/draft as having issue running `./app` locally due to sveltekit breaking changes with request object.

**Comment by Dan6erbond** [comment]
You should be able to finish the implementation of this provider now that I've merged #69! Thank you for everyone's patience!

**Comment by dwagio** [comment]
@alexstaroselsky Is there anything left to add to this? Would love to see this provider make it in!

**Comment by alexstaroselsky** [comment]
@dwagio Trying, but getting a lot of different errors and warnings try to build or run `app/`, even after syncing upstream. Making difficult, if not impossible to validate the newly added logic.

**Comment by dwagio** [comment]
Looks like there's been a ton of breaking changes in SvelteKit that actually has broken the main branch here, too.

**Comment by dwagio** [comment]
PR created: https://github.com/Dan6erbond/sk-auth/pull/81

I'm not 100% certain this fixes _everything_ but that's just because I'm having trouble configuring the needed environment variables and getting HTTPS working. As far as I can tell it works up to the point of callback.

**Comment by vhscom** [comment]
Left feedback in #81. I think @alexstaroselsky stopped because they're still blocked by app errors. Alexander, is there a specific error you need help getting past so we can wrap this up and get it merge-ready?

**Comment by alexstaroselsky** [comment]
Yes, I'm trying to avoid possibly wasting any time trying to resolve the conflicts/issues until they have been reasonably resolved.

**Comment by vhscom** [comment]
> Yes, I'm trying to avoid possibly wasting any time trying to resolve the conflicts/issues until they have been reasonably resolved.

Got it. I've got a clean build of SK Auth running on the latest version of SvelteKit with an example GitHub implementation [here](https://svelte-headlessui-starter.vercel.app) if you're interested in sending up a pull [to my fork](https://github.com/vhscom/sveltekit-oauth) so we can unblock your provider addition. If not, that's okay too.

**Comment by alexstaroselsky** [comment]
@vhscom It would still depend on this repo's PR such as https://github.com/Dan6erbond/sk-auth/pull/81 and any other related ones being completed to actually get this discord provider feature in effectively right? If you prefer, I can close this PR and you can take over this feature.

**Comment by vhscom** [comment]
I've addressed #81 in the fork plus more recent changes to SvelteKit which change those changes. If you considered the starter the `app` then you have a playground to test your changes without friction. Getting it merged with SK Auth would be a 2-line refactoring when you're finished to make it work for all SK Auth users.

**Comment by alexstaroselsky** [comment]
I unfortunately do not have the time the properly focus on this feature. I'm going to close this PR and anyone interested in driving this feature home is more than welcome to use or not use anything introduced in this PR. Thanks!

**Pull request closed without merging**
