### PR TITLE
Update Svelte-kit dependency to @next.259

### PR DESCRIPTION
**Pull request by landongn**
This PR resolves a conflict in https://github.com/sveltejs/kit/pull/3384 that sk-auth was having problems with.  Resolves all providers and endpoint configurations (as well as some cookie handling) to support the new signature.  Tested with local apps and all seems well.

### CODE REVIEW

**Comment by landongn** [comment]
also added `npm prepare` which will allow you to install locally or through `npm install github:[name]/[repo]` for local testing, just in case others were flummoxed by why it didn't work when testing locally. 👍

**Comment by maverick-dev-55** [comment]
from now on i will be using your fork in my projects until this is merged

**Comment by Dan6erbond** [comment]
Oh wow. Looks like SvelteKit still has a lot of breaking changes, but thanks for the PR! I've gone ahead and done some style changes as well as removed the `package-lock.json` file and will be merging it in a moment.

**Comment by vhscom** [comment]
@Dan6erbond ci failed to push to npm as there was no bump in the package. if your still planning to push up a new version please excuse the intrusion. otherwise please note npm isn't updated yet :) p.s. let me highly recommend [changesets](https://github.com/changesets/changesets) for versioning and changelogs. it's low friction, supports mono and regular repos and is currently used by the team working on kit.

**Pull request merged**
