### PR TITLE
feat: spotify provider

### PR DESCRIPTION
**Pull request by alexstaroselsky**
Add provider for Spotify

### CODE REVIEW

**Comment by alexstaroselsky** [comment]
Supporting documentation:

- https://developer.spotify.com/documentation/general/guides/authorization/code-flow/
- https://developer.spotify.com/documentation/web-api/reference/#/operations/get-current-users-profile

**Comment by Dan6erbond** [comment]
Nice! Simple enough to work with, look forward to playing around with it.

**Comment by alexstaroselsky** [comment]
Prettier linting was failing around syntax in `README.md` and prettier format was causing markdown to loss emphasis for that block. Update syntax of the block related to `VITE_` environment variables to pass lint while maintaining emphasis.

**Comment by alexstaroselsky** [comment]
Maybe README.md can be added to prettier ignore? Format does some interesting things to the README. Changes:

```md
***Warning**: env variables prefixed with `VITE_` can be exposed and leaked into client-side bundles if they are referenced in any client-side code. Make sure this is not the case, or consider using an alternative method such as loading them via dotenv directly instead.*
```

to

```md
**\*Warning**: env variables prefixed with `VITE_` can be exposed and leaked into client-side bundles if they are referenced in any client-side code. Make sure this is not the case, or consider using an alternative method such as loading them via dotenv directly instead.\*
```

Similar thing was happening with the existing version of `README.md` for this block, the adding of the `\` character.

**Comment by Dan6erbond** [comment]
Nice! Merged.

> Maybe README.md can be added to prettier ignore? Format does some interesting things to the README. Changes:
> 
> ```lisp
> ***Warning**: env variables prefixed with `VITE_` can be exposed and leaked into client-side bundles if they are referenced in any client-side code. Make sure this is not the case, or consider using an alternative method such as loading them via dotenv directly instead.*
> ```
> 
> to
> 
> ```lisp
> **\*Warning**: env variables prefixed with `VITE_` can be exposed and leaked into client-side bundles if they are referenced in any client-side code. Make sure this is not the case, or consider using an alternative method such as loading them via dotenv directly instead.\*
> ```
> 
> Similar thing was happening with the existing version of `README.md` for this block, the adding of the `\` character.

Just added `README.md` to the `.prettierignore` to deal with this issue! Thanks for pointing it out.

**Pull request merged**
