### PR TITLE
fix: rename endpoint method to uppercase

### PR DESCRIPTION
**Pull request by leovoon**
To fit sveltekit's recent update, should use uppercase GET and POST.

### CODE REVIEW

**Comment by Dan6erbond** [comment]
@leovoon thanks for this PR. As #75 was just merged, could you rebase so that we don't have conflicts?

**Comment by Dan6erbond** [comment]
The lint job also fails...

**Comment by leovoon** [comment]
> The lint job also fails... Try running Prettier.

Should be OK now.

**Comment by imawaki** [comment]
Hello, thank you for this great improvement. How can I take this commit take effect in my project?
I mean, this was merged yesterday but the npm latest version (0.4.1) was published 5 months ago.
I tried `npm rm sk-auth` && `npm install sk-auth@next` but did not work. I'm rather new to front-end development.
Thank you in advance 🙏 @leovoon @Dan6erbond

**Comment by imawaki** [comment]
`$ npm i git+https://github.com/Dan6erbond/sk-auth.git` was what I wanted to do. deleted my silly question, thank you 🙏

**Comment by leovoon** [comment]
> `$ npm i git+https://github.com/Dan6erbond/sk-auth.git` was what I wanted to do. deleted my silly question, thank you 🙏

I learned from you, it wasn't a silly question ❤️

**Pull request merged**
